### ISSUE TITLE
BLIP safetensors file does not work

### ISSUE THREAD

**Issue by aliencaocao** [microsoft/OmniParser#30]
![Image](https://github.com/user-attachments/assets/b6b54c9e-34e9-4c81-9a92-0dcefe3fe0d7)
~~Is this even tested? Or something went wrong?~~

EDIT: it works only if you use the pytorch bins and index file from the omniparser HF repo, not if you use safetensors with the index file from [original model's HF repo](https://huggingface.co/Salesforce/blip2-opt-2.7b/blob/main/model.safetensors.index.json).

**Comment by yadong-lu** [comment]
It should work if you download the files from the HF repo. Feel free to update if it doesn't work for you.

**Comment by aliencaocao** [comment]
Yes only the pt files work, the safetensor files in the HF repo don't work due to lack of index json, and if I borrow the index json from the original model, it loads the weight wrongly.
So there fix would be either to remove the safetensors from your HF repo, or add  your version of the index.json.
This also causes https://github.com/microsoft/OmniParser/issues/8, when the weights are indeed there but it is missing the index json.

**Comment by yadong-lu** [comment]
> Yes only the pt files work, the safetensor files in the HF repo don't work due to lack of index json, and if I borrow the index json from the original model, it loads the weight wrongly. So there fix would be either to remove the safetensors from your HF repo, or add your version of the index.json. This also causes [#8](https://github.com/microsoft/OmniParser/issues/8), when the weights are indeed there but it is missing the index json.

which caption model you are referring to? I just to download a clean copy of weights from current hf repo: https://huggingface.co/microsoft/OmniParser/tree/main, and didn't encounter any problem of loading for both finetuning blip2 and florence. 

Also I checked the output using blip2, the result makes sense to me:
![Image](https://github.com/user-attachments/assets/97d9b071-0d5c-488d-b8f9-10915cf639f9)

**Comment by aliencaocao** [comment]
If you only download the safetensors and not .pt file. They are duplicates and only one of them is needed. Else, you would be downloading 2x the weights at 14gb

**Comment by abrichr** [comment]
Confirmed working with `huggingface_hub` weights downloaded via [`download.py`](https://github.com/microsoft/OmniParser/pull/52/files#diff-0754e2389b0a4982ce0106c260cf218699e6f2061105043cc24acc7398d1d38b) in https://github.com/microsoft/OmniParser/pull/52:

![Image](https://github.com/user-attachments/assets/8eb93df0-0105-493c-bec4-5dbf31169c5c)

(Also extended to return bounding boxes.)

**Comment by aliencaocao** [comment]
Yes if you download using huggingface_hub it downloads the duplicated weight files, which includes the correct file, and also the not working file that i have been referring to.

**Comment by yadong-lu** [comment]
@aliencaocao
I checked the commit history, it seems safetensors are added automatically by HF in this commit (which is strange): https://huggingface.co/microsoft/OmniParser/commit/43bce5b3ddbbfce86b49fa08ae02dd5b55b41fc0. 

I loaded this safetensor file and the output is nonsense. I will remove the safetensor file for now and default to .bin file for model weights.

**Comment by aliencaocao** [comment]
Yep that would clear the confusion for new users. Thanks
