### ISSUE TITLE
requirements.txt error

### ISSUE THREAD

**Issue by STSonyThomas** [microsoft/OmniParser#38]
![Image](https://github.com/user-attachments/assets/33b180a3-c540-4aff-b925-96e1d7dbb860)
This is the error.

I know this is a simple fix but then can I make a PR to make the fix?

**Comment by nmstoker** [comment]
It'd be better to wait for one of the five other PRs that already exist to solve this get accepted!

**Comment by STSonyThomas** [comment]
Didn't see that. Sorry about that.
