### ISSUE TITLE
error when run gradio_demo.py

### ISSUE THREAD

**Issue by jachenms** [microsoft/OmniParser#62]
![Image](https://github.com/user-attachments/assets/c1416c01-c9ec-40ed-86f3-a32caf4364c3)
  I use CPU , change code with device =cpu depending on the attached snapshot![Image](https://github.com/user-attachments/assets/ec2bdd1d-b673-42fe-9892-f51cfa8da7ab)

appreciate to help me to solve the issue as soon as possible

**Comment by abrichr** [comment]
See https://github.com/microsoft/OmniParser/pull/52 for a [Dockerfile](https://github.com/microsoft/OmniParser/pull/52/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557).

**Comment by jachenms** [comment]
![Image](https://github.com/user-attachments/assets/928d08df-eb4d-4029-80a9-23a76cde542b)
 I can run but not sure if it is error on cpu , appreciated to help me to support!

**Comment by jachenms** [comment]
![Image](https://github.com/user-attachments/assets/f4673b9e-c431-45f1-b8eb-f083fc2bf6a9)
u can refer to the detail code for debug thanks!

**Comment by yadong-lu** [comment]
@jachenms  In my testing cpu is quite slow and can take a few minutes to get back the results.

**Comment by yadong-lu** [comment]
Feel free to reopen the issue if necessary.

**Comment by keyserjaya** [comment]
i fixed it, via reinstall `torchvision` to CUDA version.
```
pip uninstall torchvision -y
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124
```
