### ISSUE TITLE
Issues with running omniparser via hugging face.

### ISSUE THREAD

**Issue by techsparkling** [microsoft/OmniParser#69]
Hey i am getting this error when making use of huggingface to execute omniparser.
```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/microsoft/OmniParser/resolve/main/preprocessor_config.json
```

**Comment by yadong-lu** [comment]
can you specify the set-up and env you use? 

Also feel free to play with our demo: https://huggingface.co/spaces/microsoft/OmniParser

**Comment by yadong-lu** [comment]
feel free to reopen if you have further questions.
