### ISSUE TITLE
Error in Chinese characters OCR results, Illegal instruction

### ISSUE THREAD

**Issue by future911** [microsoft/OmniParser#77]
If the image contains Chinese text during recognition, it will be recognized as garbled.
I have changed the language setting of PaddleOCR to CH , but an error occurred when running python gradio_demo. py.

`
[OmniParser/utils.py](https://github.com/microsoft/OmniParser/blob/d1b39a2bddfa23049f3f328595d87810b71401e1/utils.py#L21-L31)

Lines 21 to 31 in [d1b39a2](https://github.com/microsoft/OmniParser/commit/d1b39a2bddfa23049f3f328595d87810b71401e1)

from paddleocr import PaddleOCR
reader = easyocr.Reader(['en'])
paddle_ocr = PaddleOCR(
lang='en', # other lang also available
use_angle_cls=False,
use_gpu=False, # using cuda will conflict with pytorch in the same process
show_log=False,
max_batch_size=1024,
use_dilation=True, # improves accuracy
det_db_score_mode='slow', # improves accuracy
rec_batch_num=1024)

Line 24: set PaddleOCR language to 'ch'
`

`
(omni) root@dgx:/usr/local/anaconda3/envs/omni/OmniParser# python gradio_demo.py

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
1   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
2   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
3   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
4   paddle::AnalysisPredictor::OptimizeInferenceProgram()
5   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
6   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
7   paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Graph> >)
8   paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
9   paddle::framework::ir::SelfAttentionFusePass::ApplyImpl(paddle::framework::ir::Graph*) const
10  paddle::framework::ir::GraphPatternDetector::operator()(paddle::framework::ir::Graph*, std::function<void (std::map<paddle::framework::ir::PDNode*, paddle::framework::ir::Node*, paddle::framework::ir::GraphPatternDetector::PDNodeCompare, std::allocator<std::pair<paddle::framework::ir::PDNode* const, paddle::framework::ir::Node*> > > const&, paddle::framework::ir::Graph*)>)

----------------------
Error Message Summary:
----------------------
FatalError: `Illegal instruction` is detected by the operating system.
  [TimeInfo: *** Aborted at 1730946777 (unix time) try "date -d @1730946777" if you are using GNU date ***]
  [SignalInfo: *** SIGILL (@0x7f4e6328860a) received by PID 2482377 (TID 0x7f5057a7b740) from PID 1663600138 ***]

Illegal instruction (core dumped)

`

![Image](https://github.com/user-attachments/assets/c812d99d-4ae0-46ff-a858-1ba195e76ff3)

**Comment by binnn6** [comment]
try  `pip install paddlepaddle==3.0.0b1 `

https://github.com/PaddlePaddle/PaddleOCR/issues/13327

**Comment by future911** [comment]
> try `pip install paddlepaddle==3.0.0b1 `
> 
> [#27](https://github.com/microsoft/OmniParser/issues/27) [PaddlePaddle/PaddleOCR#13327](https://github.com/PaddlePaddle/PaddleOCR/issues/13327)

thks!
