### ISSUE TITLE
OSError: microsoft/OmniParser does not appear to have a file named preprocessor_config.json.

### ISSUE THREAD

**Issue by GustawB** [microsoft/OmniParser#80]
I tried to use the model directly from the Hugging face portal.
After running code below both in Pycharm with Jupiter server and Google collab:

`# Load model directly
from transformers import AutoProcessor, AutoModelForVisualQuestionAnswering

processor = AutoProcessor.from_pretrained("microsoft/OmniParser")
model = AutoModelForVisualQuestionAnswering.from_pretrained("microsoft/OmniParser")`

I got error: OSError: microsoft/OmniParser does not appear to have a file named preprocessor_config.json. Checkout 'https://huggingface.co/microsoft/OmniParser/tree/main' for available files..

It seems I'm not the only one with this issue: https://huggingface.co/microsoft/OmniParser/discussions/20

**Comment by berkantay** [comment]
@GustawB How did you able to run with transformers?

**Comment by GustawB** [comment]
@berkantay My understanding is that hugging face repo is not really meant to be run with transformers. It only contains weights that needs to be downloaded in order to run the github repo. So if you want to play with the OmniParser, cloning github repo and following the tutorial seems like the only "normal" solotion to run it.

**Comment by berkantay** [comment]
@GustawB Thank you for the clarification. I actually couldn't wait and started to play with it on a serverless GPU environment. But it could be much much simpler with the transformers anyways.
